server:
  port: 8085

spring:
  application:
    name: checkout
  jmx:
    enabled: true
  activemq:
    broker-url: "tcp://localhost:61616"
  jpa:
    properties:
      "hibernate.jdbc.log.warnings": "false"
  sql:
    init:
      platform: hsqldb

management:
  metrics:
    distribution:
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
  endpoints:
    jmx:
      exposure:
        include: beans,mappings
    web:
      exposure:
        include: metrics,prometheus,health
  endpoint:
    health:
      probes:
        enabled: true