vulnerabilities:
  - id: CVE-2023-45853
    statement: "zlib vulnerability in Debian 12.13 base image, no fix available"
    expired_at: 2026-09-01
  - id: CVE-2026-25210
    statement: Wait for upstream fix in debian
    expired_at: 2026-09-01
  - id: CVE-2025-69720
    statement: Wait for upstream fix in debian
    expired_at: 2026-09-01
  - id: CVE-2023-45853
    statement: Wait for upstream fix in debian
    expired_at: 2026-09-01
  - id: CVE-2026-45186
    statement: Waiting for debian upstream fix
    expired_at: 2026-09-01
  - id: CVE-2025-59375
    statement: Waiting for debian upstream fix
    expired_at: 2026-09-01
  - id: CVE-2026-42496
    statement: Waiting for debian upstream fix
    expired_at: 2026-09-01
  - id: CVE-2026-8376
    statement: Waiting for debian upstream fix
    expired_at: 2026-09-01
  - id: CVE-2026-42497
    statement: Waiting for debian upstream fix
    expired_at: 2026-09-01
  - id: CVE-2026-9538
    statement: Waiting for debian upstream fix
    expired_at: 2026-09-01
  - id: CVE-2026-48962
    statement: Waiting for debian upstream fix
    expired_at: 2026-09-01
  - id: CVE-2026-48959
    statement: Waiting for debian upstream fix
    expired_at: 2026-09-01
  - id: CVE-2026-45447
    statement: Waiting for debian upstream fix
    expired_at: 2026-09-01
  - id: CVE-2026-54369
    statement: Waiting for debian upstream fix
    expired_at: 2026-09-01
  - id: CVE-2026-54371
    statement: Waiting for debian upstream fix
    expired_at: 2026-09-01
