

spring:
  application:
    name: order
  jmx:
    enabled: true

management:
  # This property is deprecated: Should be applied at the ObservationRegistry level.
            # percentiles: 0.95
  endpoints:
    jmx:
      exposure:
        include: beans,mappings
    web:
      exposure:
        include: metrics,prometheus,health
  endpoint:
    health:
      probes:
        enabled: true
server:
  port: 8086