

spring:
  application:
    name: order
  jmx:
    enabled: true

management:
  metrics:
    web:
      server:
        request:
          autotime:
            percentiles: 0.95
  endpoints:
    jmx:
      exposure:
        include: beans,mappings
    web:
      exposure:
        include: metrics,prometheus,health
  endpoint:
    health:
      probes:
        enabled: true
server:
  port: 8086