{{- if and .Values.gateway.enabled .Values.gateway.ingress.haproxy.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-haproxy-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with .Values.gateway.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: haproxy
  rules:
  {{- $host := .Values.gateway.ingress.haproxy.host | default .Values.gateway.ingress.host }}
  {{- if $host }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 80
  {{- else }}
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 80
  {{- end }}
{{- end -}}
