{{- if and .Values.gateway.enabled .Values.gateway.ingress.openshift.enabled .Values.gateway.ingress.openshift.tls.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gateway.ingress.openshift.tls.secretName }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.gateway.ingress.openshift.tls.cert | b64enc }}
  tls.key: {{ .Values.gateway.ingress.openshift.tls.key | b64enc }}
{{- end -}}

