---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: steadybit-demo
      namespace: steadybit-demo
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: steadybit-demo:view
      namespace: steadybit-demo
    roleRef:
      kind: ClusterRole
      apiGroup: rbac.authorization.k8s.io
      name: view
    subjects:
      - kind: Group
        name: system:serviceaccounts:steadybit-demo
        apiGroup: rbac.authorization.k8s.io




