---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: steadybit-demo
  labels:
    run: gateway
    service-tier: "1"
    domain: "shop-gateway"
    tags.datadoghq.com/service: shop-gateway
    tags.datadoghq.com/version: 1.0.0
  name: gateway
spec:
  replicas: {{ .Values.gateway.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      run: gateway-exposed
  template:
    metadata:
      labels:
        run: gateway-exposed
        service-tier: "1"
        domain: "shop-gateway"
        tags.datadoghq.com/service: shop-gateway
        tags.datadoghq.com/version: 1.0.0
    spec:
      serviceAccountName: steadybit-demo
      containers:
        - image: {{ .Values.gateway.image.name}}:{{ .Values.gateway.image.tag }}
          imagePullPolicy: Always
          name: gateway
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
              ephemeral-storage: "500Mi"
            limits:
              memory: "512Mi"
              cpu: "1000m"
              ephemeral-storage: "1Gi"
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Dsun.net.inetaddr.ttl=0"
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60
          volumeMounts:
            - name: work-dir
              mountPath: /work
      volumes:
        - name: work-dir
          emptyDir:
            sizeLimit: 256Mi
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: run
                    operator: In
                    values:
                      - gateway-exposed
              topologyKey: "topology.kubernetes.io/zone"
---
apiVersion: v1
kind: Service
metadata:
  namespace: steadybit-demo
  labels:
    run: gateway
  name: gateway
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    run: gateway-exposed
  type: LoadBalancer
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gateway-pdb
  namespace: steadybit-demo
spec:
  minAvailable: 1
  selector:
    matchLabels:
      run: gateway-exposed