{{- if .Values.bestsellerFashion.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    run: fashion-bestseller
    service-tier: "2"
    domain: "shop-products"
    tags.steadybit.com/service-validation: "http"
    tags.datadoghq.com/service: shop-products
    tags.datadoghq.com/version: 1.0.0
  name: fashion-bestseller
spec:
  replicas: {{ .Values.bestsellerFashion.replicaCount }}
  selector:
    matchLabels:
      run: fashion-bestseller-exposed
  template:
    metadata:
      labels:
        run: fashion-bestseller-exposed
        service-tier: "2"
        domain: "shop-products"
        tags.steadybit.com/service-validation: "http"
        tags.datadoghq.com/service: shop-products
        tags.datadoghq.com/version: 1.0.0
      {{- with .Values.global.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: steadybit-demo
      containers:
        - image: {{ .Values.bestsellerFashion.image.name}}:{{ .Values.bestsellerFashion.image.tag }}
          name: fashion-bestseller
          imagePullPolicy: Always
          resources: {{ toYaml .Values.bestsellerFashion.resources | nindent 14 }}
          ports:
            - containerPort: 8082
              protocol: TCP
          env:
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
            - name: rest.endpoint.inventory
              value: {{ .Values.global.endpoints.inventory }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 60
            timeoutSeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 10
      {{- with .Values.bestsellerFashion.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      imagePullSecrets:
        - name: regcredinternal
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    run: fashion-bestseller
  name: fashion-bestseller
spec:
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    run: fashion-bestseller-exposed
  type: ClusterIP
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: fashion-bestseller-pdb
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      run: fashion-bestseller-exposed
{{- end -}}