---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: steadybit-demo
  labels:
    run: toys-bestseller
    service-tier: "2"
    domain: "shop-products"
    tags.datadoghq.com/service: shop-products
    tags.datadoghq.com/version: 1.0.0
  name: toys-bestseller
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      run: toys-bestseller-exposed
  template:
    metadata:
      labels:
        run: toys-bestseller-exposed
        service-tier: "2"
        domain: "shop-products"
        tags.datadoghq.com/service: shop-products
        tags.datadoghq.com/version: 1.0.0
    spec:
      serviceAccountName: steadybit-demo
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: run
                    operator: In
                    values:
                      - toys-bestseller-exposed
              topologyKey: "topology.kubernetes.io/zone"
      containers:
        - image: steadybit/bestseller-toys:develop
          imagePullPolicy: Always
          name: toys-bestseller
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
              ephemeral-storage: "500Mi"
            limits:
              memory: "512Mi"
              cpu: "1000m"
              ephemeral-storage: "1Gi"
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 40
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 40
      imagePullSecrets:
        - name: regcredinternal
---
apiVersion: v1
kind: Service
metadata:
  namespace: steadybit-demo
  labels:
    run: toys-bestseller
  name: toys-bestseller
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    run: toys-bestseller-exposed
  type: ClusterIP
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: toys-bestseller-pdb
  namespace: steadybit-demo
spec:
  minAvailable: 1
  selector:
    matchLabels:
      run: toys-bestseller-exposed