---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: steadybit-demo
  labels:
    run: checkout
    service-tier: "1"
    domain: "shop-checkout"
    tags.datadoghq.com/service: shop-checkout
    tags.datadoghq.com/version: 1.0.0
  name: checkout
spec:
  replicas: {{ .Values.checkout.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      run: checkout
  template:
    metadata:
      labels:
        run: checkout
        service-tier: "1"
        domain: "shop-checkout"
        tags.datadoghq.com/service: shop-checkout
        tags.datadoghq.com/version: 1.0.0
      {{- with .Values.global.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: steadybit-demo
      containers:
        - image: {{ .Values.checkout.image.name}}:{{ .Values.checkout.image.tag }}
          resources: {{ toYaml .Values.checkout.resources | nindent 14 }}
          imagePullPolicy: Always
          name: checkout
          ports:
            - containerPort: 8085
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8085
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8085
            initialDelaySeconds: 60
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: run
                    operator: In
                    values:
                      - checkout
              topologyKey: "topology.kubernetes.io/zone"
      {{- with .Values.checkout.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      imagePullSecrets:
        - name: regcredinternal
---
apiVersion: v1
kind: Service
metadata:
  namespace: steadybit-demo
  labels:
    run: checkout
  name: checkout
spec:
  ports:
    - port: 8085
      protocol: TCP
      targetPort: 8085
  selector:
    run: checkout
  type: ClusterIP
{{ if eq .Values.checkout.horizontalPodAutoscaler true }}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: checkout-hpa
  namespace: steadybit-demo
spec:
  maxReplicas: 3
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: checkout
  targetCPUUtilizationPercentage: 200 # targets request (not limit)
{{ end }}
{{ if eq .Values.checkout.podDisruptionBudget true }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: checkout-pdb
  namespace: steadybit-demo
spec:
  minAvailable: 1
  selector:
    matchLabels:
      run: checkout
{{ end }}