apiVersion: v2
name: steadybit-shopping-demo
description: Steadybit shopping-demo application Helm chart for Kubernetes.
version: 1.2.0
appVersion: latest
type: application
home: https://www.steadybit.com/
icon: https://steadybit-website-assets.s3.amazonaws.com/logo-symbol-transparent.png
maintainers:
  - email: ansgar.schulte@steadybit.com
    name: ansgarschulte
sources:
  - https://github.com/steadybit/shopping-demo
annotations:
  artifacthub.io/images: |
    - name: logo
      image: https://steadybit-website-assets.s3.amazonaws.com/logo-symbol-transparent.png
  artifacthub.io/links: |-
    - name: Steadybit website
      url: https://www.steadybit.com
    - name: Steadybit reliability hub
      url: https://hub.steadybit.com

dependencies:
  - name: kubernetes-ingress
    version: "*"
    repository: "oci://ghcr.io/haproxytech/helm-charts"
    alias: haproxy
    condition: gateway.ingress.haproxy.enabled
  - name: redis
    version: "~20"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: redis.enabled
  - name: kafka
    version: "~31"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: kafka.enabled
  - name: rabbitmq
    version: "~16"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: rabbitmq.enabled
