# Default values for shopping-demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  podAnnotations: {}
  # Endpoints for services to use
  endpoints:
    bestsellerFashion: "http://fashion-bestseller:8082/products"
    bestsellerToys: "http://toys-bestseller:8081/products"
    hotDeals: "http://hot-deals:8083/products"
    checkout: "http://checkout:8085"
    inventory: "http://inventory:8084"
gateway:
  enabled: true
  # Container image
  image:
    # Container image name
    name: steadybit/gateway
    # Container image tag
    tag: develop
  # Container resources
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
      ephemeral-storage: "100Mi"
    limits:
      memory: "1024Mi"
      cpu: "500m"
      ephemeral-storage: "500Mi"
  # Number of gateway replicas
  replicaCount: 1
  service:
    type: LoadBalancer
  # Ingress configuration
  ingress:
    # Standard ingress configuration
    enabled: true # Set to false to disable the standard ingress
    # Hostname for the ingress
    host: null
    # Annotations for the ingress
    annotations:
    # HAProxy configuration
    haproxy:
      enabled: false  # Set to true to install HAProxy and create an ingress for gateway
      controller:
        service:
          type: NodePort
      host: null  # Custom host for HAProxy ingress (if null, uses gateway.ingress.host)
  # nodeSelector -- Node labels for pod assignment
  nodeSelector: {}
bestsellerFashion:
  enabled: true
  image:
    # Container image name
    name: steadybit/bestseller-fashion
    # Container image tag
    tag: develop
  # Container resources
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
      ephemeral-storage: "100Mi"
    limits:
      memory: "1024Mi"
      cpu: "500m"
      ephemeral-storage: "500Mi"
  # Number of bestsellerFashion replicas
  replicaCount: 1
  # nodeSelector -- Node labels for pod assignment
  nodeSelector: {}
bestsellerToys:
  enabled: true
  image:
    # Container image name
    name: steadybit/bestseller-toys-go
    # Container image tag
    tag: develop
  # Container resources
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
      ephemeral-storage: "100Mi"
    limits:
      memory: "1024Mi"
      cpu: "500m"
      ephemeral-storage: "500Mi"
  # Number of bestsellerToys replicas
  replicaCount: 1
  # nodeSelector -- Node labels for pod assignment
  nodeSelector: {}
hotDeals:
  enabled: true
  image:
    # Container image name
    name: steadybit/hot-deals
    # Container image tag
    tag: develop
  # Container resources
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
      ephemeral-storage: "100Mi"
    limits:
      memory: "1024Mi"
      cpu: "500m"
      ephemeral-storage: "500Mi"
  # Container nginx resources
  nginx:
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
        ephemeral-storage: "100Mi"
      limits:
        memory: "1024Mi"
        cpu: "500m"
        ephemeral-storage: "500Mi"
  # Number of hotDeals replicas
  replicaCount: 1
  # Enable podAffinity
  podAffinity: false
  # Service type
  service:
    type: NodePort
  # Enable podDisruptionBudget
  podDisruptionBudget: false
  # nodeSelector -- Node labels for pod assignment
  nodeSelector: {}
inventory:
  enabled: true
  image:
    # Container image name
    name: steadybit/inventory-go
    # Container image tag
    tag: develop
  # Container resources
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
      ephemeral-storage: "100Mi"
    limits:
      memory: "1024Mi"
      cpu: "500m"
      ephemeral-storage: "500Mi"
  # Number of inventory replicas
  replicaCount: 1
  # nodeSelector -- Node labels for pod assignment
  nodeSelector: {}
activemq:
  enabled: true
  image:
    # Container image name
    name: symptoma/activemq
    # Container image tag
    tag: 5.18.3
  # Container resources
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
      ephemeral-storage: "100Mi"
    limits:
      memory: "1024Mi"
      cpu: "500m"
      ephemeral-storage: "500Mi"
  # Number of activemq replicas
  replicaCount: 1
  # nodeSelector -- Node labels for pod assignment
  nodeSelector: {}
checkout:
  enabled: true
  image:
    # Container image name
    name: steadybit/checkout-go
    # Container image tag
    tag: develop
  # Container resources
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
      ephemeral-storage: "250Mi"
    limits:
      memory: "1024Mi"
      cpu: "250m"
      ephemeral-storage: "500Mi"
  # Number of checkout replicas
  replicaCount: 1
  # Enable horizontalPodAutoscaler
  horizontalPodAutoscaler: false
  # Enable podDisruptionBudget
  podDisruptionBudget: false
  # nodeSelector -- Node labels for pod assignment
  nodeSelector: {}
  activeMQ:
    # ActiveMQ Host
    host: "activemq.steadybit-shopping-demo.svc.cluster.local:61613"
orders:
  enabled: true
  image:
    # Container image name
    name: steadybit/orders-go
    # Container image tag
    tag: develop
  # Container resources
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
      ephemeral-storage: "250Mi"
    limits:
      memory: "1024Mi"
      cpu: "500m"
      ephemeral-storage: "500Mi"
  # Number of orders replicas
  replicaCount: 1
  # Enable podAffinity
  podAffinity: false
  # Enable podDisruptionBudget
  podDisruptionBudget: false
  # nodeSelector -- Node labels for pod assignment
  nodeSelector: {}
  activeMQ:
    # ActiveMQ Host
    host: "activemq.steadybit-shopping-demo.svc.cluster.local:61613"
