# Default values for shopping-demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

gateway:
  # Container image
  image:
    # Container image name
    name: steadybit/gateway
    # Container image tag
    tag: develop
  # Number of gateway replicas
  replicaCount: 1
  # Ingress configuration
  ingress:
    # Hostname for the ingress
    host: null
    # Annotations for the ingress
    annotations:
  # nodeSelector -- Node labels for pod assignment
  nodeSelector: {}
bestsellerFashion:
  image:
    # Container image name
    name: steadybit/bestseller-fashion
    # Container image tag
    tag: develop
  # Number of bestsellerFashion replicas
  replicaCount: 1
  # nodeSelector -- Node labels for pod assignment
  nodeSelector: {}
bestsellerToys:
  image:
    # Container image name
    name: steadybit/bestseller-toys
    # Container image tag
    tag: develop
  # Number of bestsellerToys replicas
  replicaCount: 1
  # nodeSelector -- Node labels for pod assignment
  nodeSelector: {}
hotDeals:
  image:
    # Container image name
    name: steadybit/hot-deals
    # Container image tag
    tag: develop
  # Number of hotDeals replicas
  replicaCount: 1
  # Enable podAffinity
  podAffinity: false
  # Service type
  service:
    type: NodePort
  # Enable podDisruptionBudget
  podDisruptionBudget: false
  # nodeSelector -- Node labels for pod assignment
  nodeSelector: {}
inventory:
  image:
    # Container image name
    name: steadybit/inventory
    # Container image tag
    tag: develop
  # Number of inventory replicas
  replicaCount: 1
  # nodeSelector -- Node labels for pod assignment
  nodeSelector: {}
activemq:
  image:
    # Container image name
    name: symptoma/activemq
    # Container image tag
    tag: 5.18.3
  # Number of activemq replicas
  replicaCount: 1
  # nodeSelector -- Node labels for pod assignment
  nodeSelector: {}
checkout:
  image:
    # Container image name
    name: steadybit/checkout
    # Container image tag
    tag: develop
  # Number of checkout replicas
  replicaCount: 1
  # Enable horizontalPodAutoscaler
  horizontalPodAutoscaler: false
  # Enable podDisruptionBudget
  podDisruptionBudget: false
  # nodeSelector -- Node labels for pod assignment
  nodeSelector: {}
orders:
  image:
    # Container image name
    name: steadybit/orders
    # Container image tag
    tag: develop
  # Number of orders replicas
  replicaCount: 1
  # Enable podAffinity
  podAffinity: false
  # Enable podDisruptionBudget
  podDisruptionBudget: false
  # nodeSelector -- Node labels for pod assignment
  nodeSelector: {}
