server:
  port: 8080

spring:
  application:
    name: gateway
  jmx:
    enabled: true

management:
  metrics:
    web:
      server:
        request:
          autotime:
            percentiles: 0.95
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health,mappings
  endpoint:
    health:
      probes:
        enabled: true

resilience4j:
  retry:
    instances:
      fashion:
        maxRetryAttempts: 3
        waitDuration: 500ms
      toys:
        maxRetryAttempts: 3
        waitDuration: 500ms
      hotdeals:
        maxRetryAttempts: 3
        waitDuration: 500ms
  circuitbreaker:
    instances:
      fashion:
        failureRateThreshold: 50
        slidingWindowType: TIME_BASED
        slidingWindowSize: 10
      toys:
        failureRateThreshold: 50
        slidingWindowType: TIME_BASED
        slidingWindowSize: 10
      hotdeals:
        failureRateThreshold: 50
        slidingWindowType: TIME_BASED
        slidingWindowSize: 10

rest:
  endpoint:
    fashion: "http://localhost:8082/products"
    toys: "http://localhost:8081/products"
    hotdeals: "http://localhost:8083/products"
    checkout: "http://localhost:8085/"