rest:
  endpoint:
    fashion: "http://fashion:8082/products"
    toys: "http://toys:8081/products"
    hotdeals: "http://hot-deals:8083/products"
    checkout: "http://checkout:8085/checkout"
    inventory: "http://inventory:8084/inventory"