server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
    kubernetes:
      enabled: false
management:
  metrics:
    web:
      server:
        request:
          autotime:
            percentiles: 0.95
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health
  endpoint:
    health:
      probes:
        enabled: true

hystrix:
  metrics:
    enabled: true
  command:
    fashion:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
    hotdeals:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
    toys:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000

resilience4j:
  retry:
    instances:
      productSearch:
        maxRetryAttempts: 3
        waitDuration: 500ms
  circuitbreaker:
    instances:
      productSearch:
        failureRateThreshold: 50
        slidingWindowType: TIME_BASED
        slidingWindowSize: 10

rest:
  endpoint:
    fashion: "http://localhost:8082/products"
    toys: "http://localhost:8081/products"
    hotdeals: "http://localhost:8083/products"