server:
  port: 8080

spring:
  jmx:
    enabled: true

management:
  health:
    circuitbreakers:
      enabled: true
  metrics:
    web:
      server:
        request:
          autotime:
            percentiles: 0.95
  endpoints:
    jmx:
      exposure:
        include: beans,mappings
    web:
      exposure:
        include: metrics,prometheus,health,mappings
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

resilience4j:
  retry:
    instances:
      fashion:
        maxAttempts: 3
        waitDuration: 500ms
      toys:
        maxAttempts: 3
        waitDuration: 500ms
      hotdeals:
        maxAttempts: 3
        waitDuration: 500ms
  circuitbreaker:
    instances:
      fashion:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 100
        minimumNumberOfCalls: 10
        waitDurationInOpenState: 10000
      toys:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 100
        minimumNumberOfCalls: 10
        waitDurationInOpenState: 10000
      hotdeals:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 100
        minimumNumberOfCalls: 10
        waitDurationInOpenState: 10000

rest:
  endpoint:
    fashion: "http://localhost:8082/products"
    toys: "http://localhost:8081/products"
    hotdeals: "http://localhost:8083/products"
    checkout: "http://localhost:8085/"
    inventory: "http://localhost:8084/"