server:
  port: 8083

spring:
  application:
    name: hot-deals
  jmx:
    enabled: true
  sql:
    init:
      platform: hsqldb

management:
  metrics:
    web:
      server:
        request:
          autotime:
            percentiles: 0.95
  endpoints:
    jmx:
      exposure:
        include: beans,mappings
    web:
      exposure:
        include: metrics,prometheus,health
  endpoint:
    health:
      probes:
        enabled: true

rest:
  endpoint:
    inventory: "http://localhost:8084/inventory"