server:
  port: 8082

spring:
  application:
    name: fashion-bestseller
  datasource:
    platform: hsqldb
  jmx:
    enabled: true

management:
  metrics:
    web:
      server:
        request:
          autotime:
            percentiles: 0.95
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health
  endpoint:
    health:
      probes:
        enabled: true

rest:
  endpoint:
    inventory: "http://localhost:8084/inventory"