name: Resilience Test

on:
  workflow_dispatch:
  
jobs:
  run_experiment:
    name: Run Resilience Regression Test in Steadybit
    runs-on: ubuntu-18.04
    env:
      API_ACCESS_TOKEN: ${{ secrets.API_ACCESS_TOKEN }}
    steps:
      - name: Start Experiment via API
        run: |
          curl \ 
            -H "Authorization: accessToken $API_ACCESS_TOKEN" \
            -H "Accept: application/json"
            -H "ContentType: application/json" \
            --request POST \
            https://platform.steadybit.com/api/experiments/RESTEST-9/execute?allowParallel=true
