name: Resilience Test

on:
  workflow_dispatch:
  pull_request:
  
jobs:
  run_experiment:
    runs-on: ubuntu-latest
    steps:
    - name: Run Resilience Regression Test in Steadybit
      uses: steadybit/run-experiment@v1
      with:
        apiAccessToken: ${{ secrets.STEADYBIT_API_ACCESS_TOKEN }}
        experimentKey: 'RESTEST-9'
